"""Remove integration_code and user from Autotask

Revision ID: 200d959c77ac
Revises: 7d188068198e
Create Date: 2025-05-19 13:42:24.426298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200d959c77ac'
down_revision: Union[str, None] = '7d188068198e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotask_integrations', 'integration_code')
    op.drop_column('autotask_integrations', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotask_integrations', sa.Column('user', sa.VARCHAR(), nullable=False))
    op.add_column('autotask_integrations', sa.Column('integration_code', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
