"""remove_unnecessary_alert_fields

Revision ID: 3f09ee1a01fd
Revises: f909c6c3c62a
Create Date: 2025-07-22 14:56:58.757069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f09ee1a01fd'
down_revision: Union[str, None] = 'f909c6c3c62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unifi_alerts', 'ap_displayName')
    op.drop_column('unifi_alerts', 'ap_name')
    op.drop_column('unifi_alerts', 'ap_model')
    op.drop_column('unifi_alerts', 'gw')
    op.drop_column('unifi_alerts', 'xg')
    op.drop_column('unifi_alerts', 'sw')
    op.drop_column('unifi_alerts', 'bb')
    op.drop_column('unifi_alerts', 'sw_displayName')
    op.drop_column('unifi_alerts', 'subsystem')
    op.drop_column('unifi_alerts', 'ap')
    op.drop_column('unifi_alerts', 'sw_model')
    op.drop_column('unifi_alerts', 'sw_name')
    op.drop_column('unifi_alerts', 'dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unifi_alerts', sa.Column('dev', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('sw_name', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('sw_model', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('ap', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('subsystem', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('sw_displayName', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('bb', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('sw', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('xg', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('gw', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('ap_model', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('ap_name', sa.VARCHAR(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('ap_displayName', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
