"""Add UnifiDevice models

Revision ID: a992f538b121
Revises: 373603008e0c
Create Date: 2025-05-09 13:53:53.332076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a992f538b121'
down_revision: Union[str, None] = '373603008e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unifi_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('last_seen', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('uplink_json', sa.Text(), nullable=True),
    sa.Column('downlink_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['unifi_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unifi_device_ips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['unifi_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unifi_device_macs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['unifi_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unifi_device_macs')
    op.drop_table('unifi_device_ips')
    op.drop_table('unifi_devices')
    # ### end Alembic commands ###
