"""add_username_email_to_unifiadmin

Revision ID: b8152d6821ce
Revises: 77a3d644f45d
Create Date: 2025-07-18 15:06:27.368405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8152d6821ce'
down_revision: Union[str, None] = '77a3d644f45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unifi_admins', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unifi_admins', sa.Column('admin_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
