"""add unifi alert tables

Revision ID: c8a649e0ccd7
Revises: remove_role_from_unifi_admins
Create Date: 2025-07-22 14:26:02.443020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a649e0ccd7'
down_revision: Union[str, None] = 'remove_role_from_unifi_admins'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unifi_alert_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('unifi_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('archived', sa.String(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(), nullable=False),
    sa.Column('is_negative', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('subsystem', sa.String(), nullable=True),
    sa.Column('sw', sa.String(), nullable=True),
    sa.Column('sw_name', sa.String(), nullable=True),
    sa.Column('sw_model', sa.String(), nullable=True),
    sa.Column('sw_displayName', sa.String(), nullable=True),
    sa.Column('ap', sa.String(), nullable=True),
    sa.Column('ap_name', sa.String(), nullable=True),
    sa.Column('ap_model', sa.String(), nullable=True),
    sa.Column('ap_displayName', sa.String(), nullable=True),
    sa.Column('gw', sa.String(), nullable=True),
    sa.Column('xg', sa.String(), nullable=True),
    sa.Column('bb', sa.String(), nullable=True),
    sa.Column('dev', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['unifi_devices.id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['unifi_alert_keys.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['unifi_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'site_id', name='uq_alert_per_site')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unifi_alerts')
    op.drop_table('unifi_alert_keys')
    # ### end Alembic commands ###
