"""Add uniqueness constraints to UniFiServer

Revision ID: d980fa599b33
Revises: 918e9ed169cc
Create Date: 2025-05-08 12:13:10.545628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd980fa599b33'
down_revision: Union[str, None] = '918e9ed169cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table("unifi_servers", recreate="always") as batch_op:
        batch_op.create_unique_constraint("uq_unifi_host_port", ["host", "port"])
        batch_op.alter_column("port", existing_type=sa.Integer(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unifi_servers', type_='unique')
    op.drop_constraint('uq_unifi_host_port', 'unifi_servers', type_='unique')
    # ### end Alembic commands ###
