"""remove timestamp columns from unifi models

Revision ID: f909c6c3c62a
Revises: c8a649e0ccd7
Create Date: 2025-07-22 14:35:10.777077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f909c6c3c62a'
down_revision: Union[str, None] = 'c8a649e0ccd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unifi_admin_site_permissions', 'created_at')
    op.drop_column('unifi_admin_site_permissions', 'updated_at')
    op.drop_column('unifi_admins', 'created_at')
    op.drop_column('unifi_admins', 'updated_at')
    op.drop_column('unifi_alert_keys', 'created_at')
    op.drop_column('unifi_alert_keys', 'updated_at')
    op.drop_column('unifi_alerts', 'created_at')
    op.drop_column('unifi_alerts', 'updated_at')
    op.drop_column('unifi_servers', 'created_at')
    op.drop_column('unifi_servers', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unifi_servers', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_servers', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_alerts', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_alert_keys', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_alert_keys', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_admins', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_admins', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_admin_site_permissions', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('unifi_admin_site_permissions', sa.Column('created_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
